[package]
name = "sophus_rxx"
version = "0.1.0"
edition = "2021"

[dependencies]
rxx = { path = "../rxx" }
eigen_rxx = { path = "../eigen-rxx" }
num = "0.4"

[build-dependencies]
sophus-rxx-build = { path = "../sophus-rxx-build" }
cc = "1.0"
anyhow = "1.0"