cargo-features = ["workspace-inheritance"]

[package]
name = "eigen-rxx"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.31"
paste = "1.0"
rxx.workspace = true

[build-dependencies]
eigen-rxx-build.workspace = true
cc = "1.0.73"
anyhow = "1.0"
