[package]
name = "rxx"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0"
rxx-macro.workspace = true

[build-dependencies]
rxx-macro.workspace = true
rxx-build.workspace = true
formatx = "0.1"
cc = "1.0.73"
anyhow = "1.0.58"
strfmt = "0.2"