cargo-features = ["workspace-inheritance"]

[package]
name = "rxx"
version = "0.1.0"
edition = "2021"

[dependencies]
paste = "1.0"
rxx-macro.workspace = true

[build-dependencies]
rxx-build.workspace = true
cc = "1.0.73"
anyhow = "1.0.58"
