[package]
name = "eigen_rxx"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.31"
paste = "1.0"
rxx = { path = "../rxx"}

[build-dependencies]
eigen-rxx-build = { path = "../eigen-rxx-build" }
cc = "1.0.73"
anyhow = "1.0"
